services:
  climatch-db:
    image: postgres:16
    environment:
      - POSTGRES_USER=climatch
      - POSTGRES_PASSWORD=climatch123
      - POSTGRES_DB=climatch
    ports:
      - "5434:5432"
    volumes:
      - climatch-pgdata:/var/lib/postgresql/data

volumes:
  climatch-pgdata: